spring.config.activate.on-profile=dev

server.port=8080
server.servlet.contextPath=/SmartCityREST

spring.datasource.url=jdbc:mysql://localhost:3306/smartcitydb
spring.datasource.username=root
spring.datasource.password=Qq2r#{(jYW0;ZKw

