spring.config.activate.on-profile=dev

server.port=8080
server.servlet.contextPath=/SmartCityREST

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

