spring.config.activate.on-profile=prod

server.port=10000
server.servlet.contextPath=/SmartCityREST

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers
