package com.example.smartcityback.asset.domain.shared.enums;

public enum ErrorCode {
    DEVICE_CAPACITY_REQUIRED,
    DEVICE_CAPACITY_ZERO,
    DEVICE_CAPACITY_NEGATIVE,
    DEVICE_CAPACITY_OUT_OF_RANGE,
    DEVICE_TYPE_REQUIRED,
    DEVICE_ALREADY_EXISTS,
    DEVICE_NOT_FOUND,

    ENERGY_VALUE_REQURIED,
    ENERGY_UNIT_REQUIRED,
    ENERGY_NEGATIVE,

    TOTAL_CAPACITY_EXCEEDED,

    BUILDING_NAME_EMPTY,
    BUILDING_ADDRESS_EMPTY,
    BUILDING_ALREADY_EXISTS,
    BUILDING_NOT_FOUND,

}
